pub fn main() {}

#[test]
fn failing_test() {
    panic!("Expected failure");
}
